version: '3.8'

services:
  # 这是我们的“翻译官” - Flask Web网关
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 web_app:app
    ports:
      - "5000:5000" # 将服务器的5000端口映射到这个容器，让公网可以访问
    volumes:
      - .:/app
    depends_on:
      - ai_server

  # 这是我们的“AI专家” - Socket服务器
  ai_server:
    build: .
    command: python ai_server.py
    volumes:
      - .:/app