version: '3.8'

services:
  redis:
    image: "redis:alpine"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 web_app:app
    ports:
      - "5000:5000"
    # 移除 volumes 配置
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A worker.celery_app worker --loglevel=info
    # 移除 volumes 配置
    depends_on:
      - redis